def partiy(x):
	MASK_SIZE = 2
	BIT_MASK = 0xFFFF
	
	return (PRECOMPUTED_PARITY[(x >> (3 * MASK_SIZE)] ^
		PRECOMPUTED_PARITY[(x >> (2 * MASK_SIZE) & BIT_MASK] ^
		PRECOMPUTED_PARITY[(x >> MASK_SIZE]] & BIT_MASK] ^ PRECOMPUTED_PARITY[x & BIT_MASK]) 

